/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import javax.swing.JFrame;
/**
 *
 * @author HP
 */
public class homePage extends javax.swing.JFrame {

    /**
     * Creates new form homePage
     */
    public homePage() {
        initComponents();
        setExtendedState(getExtendedState()|JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JLabel();
        logoGrafika = new javax.swing.JLabel();
        loginSiswaButton = new javax.swing.JButton();
        loginGuruButton = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Components/Header.png"))); // NOI18N
        header.setLabelFor(header);
        getContentPane().add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        logoGrafika.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Components/logo-grafika.png"))); // NOI18N
        logoGrafika.setLabelFor(logoGrafika);
        logoGrafika.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(logoGrafika, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 130, -1, -1));

        loginSiswaButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Components/Button Siswa.png"))); // NOI18N
        loginSiswaButton.setBorder(null);
        loginSiswaButton.setBorderPainted(false);
        loginSiswaButton.setContentAreaFilled(false);
        loginSiswaButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginSiswaButton.setFocusPainted(false);
        loginSiswaButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Components/Button Siswa Hovered.png"))); // NOI18N
        loginSiswaButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Components/Button Siswa Hovered.png"))); // NOI18N
        loginSiswaButton.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Components/Button Siswa Hovered.png"))); // NOI18N
        loginSiswaButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginSiswaButtonMouseClicked(evt);
            }
        });
        getContentPane().add(loginSiswaButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 530, -1, -1));

        loginGuruButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Components/Button Guru.png"))); // NOI18N
        loginGuruButton.setBorder(null);
        loginGuruButton.setBorderPainted(false);
        loginGuruButton.setContentAreaFilled(false);
        loginGuruButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginGuruButton.setFocusPainted(false);
        loginGuruButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Components/Button Guru Hovered.png"))); // NOI18N
        loginGuruButton.setRequestFocusEnabled(false);
        loginGuruButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Components/Button Guru Hovered.png"))); // NOI18N
        loginGuruButton.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Components/Button Guru Hovered.png"))); // NOI18N
        loginGuruButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginGuruButtonMouseClicked(evt);
            }
        });
        getContentPane().add(loginGuruButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 530, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Components/Background.png"))); // NOI18N
        background.setLabelFor(background);
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginSiswaButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginSiswaButtonMouseClicked
        // TODO add your handling code here:
        loginSiswa siswaButton = new loginSiswa();
        siswaButton.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_loginSiswaButtonMouseClicked

    private void loginGuruButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginGuruButtonMouseClicked
        // TODO add your handling code here:
        loginGuru guruButton = new loginGuru();
        guruButton.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_loginGuruButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(homePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(homePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(homePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(homePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new homePage().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel background;
    public javax.swing.JLabel header;
    private javax.swing.JButton loginGuruButton;
    private javax.swing.JButton loginSiswaButton;
    public javax.swing.JLabel logoGrafika;
    // End of variables declaration//GEN-END:variables
}
