
import javax.swing.JFrame;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author HP
 */
public class loginSiswa extends javax.swing.JFrame {

    /**
     * Creates new form loginSiswa
     */
    public loginSiswa() {
        initComponents();
        setExtendedState(getExtendedState()|JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        leftHeader = new javax.swing.JLabel();
        leftLogo = new javax.swing.JLabel();
        homeButton = new javax.swing.JButton();
        leftBackground = new javax.swing.JLabel();
        loginButton = new javax.swing.JButton();
        name = new javax.swing.JLabel();
        nis = new javax.swing.JLabel();
        jurusan = new javax.swing.JLabel();
        kelas = new javax.swing.JLabel();
        inputKelas = new javax.swing.JTextField();
        inputJurusan = new javax.swing.JTextField();
        inputNIS = new javax.swing.JTextField();
        inputName = new javax.swing.JTextField();
        rightBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        leftHeader.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Components/Left Header.png"))); // NOI18N
        leftHeader.setLabelFor(leftHeader);
        getContentPane().add(leftHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        leftLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        leftLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Components/Left Logo.png"))); // NOI18N
        leftLogo.setLabelFor(leftLogo);
        getContentPane().add(leftLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, -1, -1));

        homeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Components/Button Home.png"))); // NOI18N
        homeButton.setBorder(null);
        homeButton.setBorderPainted(false);
        homeButton.setContentAreaFilled(false);
        homeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homeButton.setFocusPainted(false);
        homeButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Components/Button Home Hovered.png"))); // NOI18N
        homeButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Components/Button Home Hovered.png"))); // NOI18N
        homeButton.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Components/Button Home Hovered.png"))); // NOI18N
        homeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeButtonMouseClicked(evt);
            }
        });
        getContentPane().add(homeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 590, -1, -1));

        leftBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Components/Left Background.png"))); // NOI18N
        leftBackground.setLabelFor(leftBackground);
        getContentPane().add(leftBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        loginButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Components/Login Button.png"))); // NOI18N
        loginButton.setBorder(null);
        loginButton.setBorderPainted(false);
        loginButton.setContentAreaFilled(false);
        loginButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginButton.setFocusPainted(false);
        loginButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Components/Login Button Hovered.png"))); // NOI18N
        loginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginButtonMouseClicked(evt);
            }
        });
        getContentPane().add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 590, -1, -1));

        name.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Components/Nama Siswa.png"))); // NOI18N
        name.setLabelFor(name);
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 70, -1, -1));

        nis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Components/NIS.png"))); // NOI18N
        nis.setLabelFor(nis);
        getContentPane().add(nis, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 190, -1, -1));

        jurusan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Components/Jurusan.png"))); // NOI18N
        jurusan.setLabelFor(jurusan);
        getContentPane().add(jurusan, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 310, -1, -1));

        kelas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Components/Kelas.png"))); // NOI18N
        kelas.setLabelFor(kelas);
        getContentPane().add(kelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 440, -1, -1));

        inputKelas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        inputKelas.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        inputKelas.setToolTipText("Input kelas siswa");
        inputKelas.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 10, 4, 4));
        getContentPane().add(inputKelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 480, 570, 50));

        inputJurusan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        inputJurusan.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        inputJurusan.setToolTipText("Input jurusan siswa");
        inputJurusan.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 10, 4, 4));
        getContentPane().add(inputJurusan, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 350, 570, 50));

        inputNIS.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        inputNIS.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        inputNIS.setToolTipText("Input nomor induk siswa");
        inputNIS.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 10, 4, 4));
        getContentPane().add(inputNIS, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 230, 570, 50));

        inputName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        inputName.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        inputName.setToolTipText("Input nama siswa");
        inputName.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 10, 4, 4));
        getContentPane().add(inputName, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 110, 570, 50));

        rightBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Components/Right Background.png"))); // NOI18N
        rightBackground.setLabelFor(rightBackground);
        getContentPane().add(rightBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeButtonMouseClicked
        // TODO add your handling code here:
        homePage homeButton = new homePage();
        homeButton.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homeButtonMouseClicked

    private void loginButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginButtonMouseClicked
        // TODO add your handling code here:
        siswaPage loginButton = new siswaPage();
        loginButton.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_loginButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginSiswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton homeButton;
    private javax.swing.JTextField inputJurusan;
    private javax.swing.JTextField inputKelas;
    private javax.swing.JTextField inputNIS;
    private javax.swing.JTextField inputName;
    private javax.swing.JLabel jurusan;
    private javax.swing.JLabel kelas;
    public javax.swing.JLabel leftBackground;
    public javax.swing.JLabel leftHeader;
    private javax.swing.JLabel leftLogo;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel name;
    private javax.swing.JLabel nis;
    private javax.swing.JLabel rightBackground;
    // End of variables declaration//GEN-END:variables
}
