
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JFrame;
import koneksi.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HP
 */
public class loginGuru extends javax.swing.JFrame {

    /**
     * Creates new form loginGuru
     */
    public loginGuru() {
        initComponents();
        setExtendedState(getExtendedState()|JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        leftHeader = new javax.swing.JLabel();
        leftLogo = new javax.swing.JLabel();
        homeButton = new javax.swing.JButton();
        name = new javax.swing.JLabel();
        inputName = new javax.swing.JTextField();
        kodeGuru = new javax.swing.JLabel();
        inputNIS = new javax.swing.JTextField();
        mapel = new javax.swing.JLabel();
        inputJurusan = new javax.swing.JTextField();
        loginButton = new javax.swing.JButton();
        leftBackground = new javax.swing.JLabel();
        rightBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        leftHeader.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Components/Left Header.png"))); // NOI18N
        getContentPane().add(leftHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        leftLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Components/Left Logo.png"))); // NOI18N
        getContentPane().add(leftLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, -1, -1));

        homeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Components/Button Home.png"))); // NOI18N
        homeButton.setBorder(null);
        homeButton.setBorderPainted(false);
        homeButton.setContentAreaFilled(false);
        homeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homeButton.setFocusPainted(false);
        homeButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Components/Button Home Hovered.png"))); // NOI18N
        homeButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Components/Button Home Hovered.png"))); // NOI18N
        homeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeButtonMouseClicked(evt);
            }
        });
        getContentPane().add(homeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 590, -1, -1));

        name.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Components/Nama Guru.png"))); // NOI18N
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 140, -1, -1));

        inputName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        inputName.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        inputName.setToolTipText("Input nama siswa");
        inputName.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 10, 4, 4));
        getContentPane().add(inputName, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 180, 570, 50));

        kodeGuru.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Components/Kode Guru.png"))); // NOI18N
        getContentPane().add(kodeGuru, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 260, -1, -1));

        inputNIS.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        inputNIS.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        inputNIS.setToolTipText("Input nomor induk siswa");
        inputNIS.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 10, 4, 4));
        getContentPane().add(inputNIS, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 300, 570, 50));

        mapel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Components/Mata Pelajaran.png"))); // NOI18N
        getContentPane().add(mapel, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 380, -1, -1));

        inputJurusan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        inputJurusan.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        inputJurusan.setToolTipText("Input jurusan siswa");
        inputJurusan.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 10, 4, 4));
        getContentPane().add(inputJurusan, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 420, 570, 50));

        loginButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Components/Login Button.png"))); // NOI18N
        loginButton.setBorder(null);
        loginButton.setBorderPainted(false);
        loginButton.setContentAreaFilled(false);
        loginButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginButton.setFocusPainted(false);
        loginButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Components/Login Button Hovered.png"))); // NOI18N
        loginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginButtonMouseClicked(evt);
            }
        });
        getContentPane().add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 530, -1, -1));

        leftBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Components/Left Background.png"))); // NOI18N
        getContentPane().add(leftBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        rightBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Components/Right Background.png"))); // NOI18N
        getContentPane().add(rightBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeButtonMouseClicked
        // TODO add your handling code here:
        homePage homeButton = new homePage();
        homeButton.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homeButtonMouseClicked

    private void loginButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginButtonMouseClicked
        // TODO add your handling code here:
        System.out.println(inputJurusan.getText());
        koneksi kon = new koneksi();
        String nama_guru = inputName.getText();
        String nis_guru = inputNIS.getText();
        String mapel_guru = inputJurusan.getText();
        boolean login = kon.login_guru(nama_guru, nis_guru, mapel_guru);
        if (login){
            guruPage loginButton = new guruPage();
            loginButton.setVisible(true);
            this.dispose();
        }else{
            System.out.println("Login gagal");
        }
    }//GEN-LAST:event_loginButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginGuru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginGuru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginGuru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginGuru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginGuru().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton homeButton;
    private javax.swing.JTextField inputJurusan;
    private javax.swing.JTextField inputNIS;
    private javax.swing.JTextField inputName;
    private javax.swing.JLabel kodeGuru;
    private javax.swing.JLabel leftBackground;
    private javax.swing.JLabel leftHeader;
    private javax.swing.JLabel leftLogo;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel mapel;
    private javax.swing.JLabel name;
    private javax.swing.JLabel rightBackground;
    // End of variables declaration//GEN-END:variables
}
