
import javax.swing.JFrame;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HP
 */
public class mapelPage extends javax.swing.JFrame {

    /**
     * Creates new form mapelPage
     */
    public mapelPage() {
        initComponents();
        setExtendedState(getExtendedState()|JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JLabel();
        buttonPBO = new javax.swing.JButton();
        buttonPWPB = new javax.swing.JButton();
        buttonDB = new javax.swing.JButton();
        buttonPKKrpl = new javax.swing.JButton();
        buttonPPL = new javax.swing.JButton();
        buttonEnglish = new javax.swing.JButton();
        buttonMath = new javax.swing.JButton();
        buttonAgama = new javax.swing.JButton();
        buttonPPKN = new javax.swing.JButton();
        buttonPJOK = new javax.swing.JButton();
        buttonPKK = new javax.swing.JButton();
        buttonIndo = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Components/Header.png"))); // NOI18N
        getContentPane().add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        buttonPBO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Components/PBO.png"))); // NOI18N
        buttonPBO.setToolTipText("Button");
        buttonPBO.setBorder(null);
        buttonPBO.setBorderPainted(false);
        buttonPBO.setContentAreaFilled(false);
        buttonPBO.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonPBO.setFocusPainted(false);
        buttonPBO.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Components/PBO Hovered.png"))); // NOI18N
        buttonPBO.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Components/PBO Hovered.png"))); // NOI18N
        getContentPane().add(buttonPBO, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, -1, -1));

        buttonPWPB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Components/PWPB.png"))); // NOI18N
        buttonPWPB.setToolTipText("Button");
        buttonPWPB.setBorder(null);
        buttonPWPB.setBorderPainted(false);
        buttonPWPB.setContentAreaFilled(false);
        buttonPWPB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonPWPB.setFocusPainted(false);
        buttonPWPB.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Components/PWPB Hovered.png"))); // NOI18N
        buttonPWPB.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Components/PWPB Hovered.png"))); // NOI18N
        getContentPane().add(buttonPWPB, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, -1, 200));

        buttonDB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Components/Basis Data.png"))); // NOI18N
        buttonDB.setToolTipText("Button");
        buttonDB.setBorder(null);
        buttonDB.setBorderPainted(false);
        buttonDB.setContentAreaFilled(false);
        buttonDB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonDB.setFocusPainted(false);
        buttonDB.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Components/Basis Data Hovered.png"))); // NOI18N
        buttonDB.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Components/Basis Data Hovered.png"))); // NOI18N
        getContentPane().add(buttonDB, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 90, -1, 200));

        buttonPKKrpl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Components/PKK (RPL).png"))); // NOI18N
        buttonPKKrpl.setToolTipText("Button");
        buttonPKKrpl.setBorder(null);
        buttonPKKrpl.setBorderPainted(false);
        buttonPKKrpl.setContentAreaFilled(false);
        buttonPKKrpl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonPKKrpl.setFocusPainted(false);
        buttonPKKrpl.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Components/PKK (RPL) Hovered.png"))); // NOI18N
        buttonPKKrpl.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Components/PKK (RPL) Hovered.png"))); // NOI18N
        getContentPane().add(buttonPKKrpl, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 90, -1, 200));

        buttonPPL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Components/PPL.png"))); // NOI18N
        buttonPPL.setToolTipText("Button");
        buttonPPL.setBorder(null);
        buttonPPL.setBorderPainted(false);
        buttonPPL.setContentAreaFilled(false);
        buttonPPL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonPPL.setFocusPainted(false);
        buttonPPL.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Components/PPL Hovered.png"))); // NOI18N
        buttonPPL.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Components/PPL Hovered.png"))); // NOI18N
        getContentPane().add(buttonPPL, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, -1, -1));

        buttonEnglish.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Components/Bahasa Inggris.png"))); // NOI18N
        buttonEnglish.setToolTipText("Button");
        buttonEnglish.setBorder(null);
        buttonEnglish.setBorderPainted(false);
        buttonEnglish.setContentAreaFilled(false);
        buttonEnglish.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonEnglish.setFocusPainted(false);
        buttonEnglish.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Components/Bahasa Inggris Hovered.png"))); // NOI18N
        buttonEnglish.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Components/Bahasa Inggris Hovered.png"))); // NOI18N
        getContentPane().add(buttonEnglish, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 310, -1, -1));

        buttonMath.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Components/Math.png"))); // NOI18N
        buttonMath.setToolTipText("Button");
        buttonMath.setBorder(null);
        buttonMath.setBorderPainted(false);
        buttonMath.setContentAreaFilled(false);
        buttonMath.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonMath.setFocusPainted(false);
        buttonMath.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Components/Math Hovered.png"))); // NOI18N
        buttonMath.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Components/Math Hovered.png"))); // NOI18N
        getContentPane().add(buttonMath, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 310, -1, -1));

        buttonAgama.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Components/Agama.png"))); // NOI18N
        buttonAgama.setToolTipText("Button");
        buttonAgama.setBorder(null);
        buttonAgama.setBorderPainted(false);
        buttonAgama.setContentAreaFilled(false);
        buttonAgama.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonAgama.setFocusPainted(false);
        buttonAgama.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Components/Agama Hovered.png"))); // NOI18N
        buttonAgama.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Components/Agama Hovered.png"))); // NOI18N
        getContentPane().add(buttonAgama, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 310, -1, -1));

        buttonPPKN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Components/PPKN.png"))); // NOI18N
        buttonPPKN.setToolTipText("Button");
        buttonPPKN.setBorder(null);
        buttonPPKN.setBorderPainted(false);
        buttonPPKN.setContentAreaFilled(false);
        buttonPPKN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonPPKN.setFocusPainted(false);
        buttonPPKN.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Components/PPKN Hovered.png"))); // NOI18N
        buttonPPKN.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Components/PPKN Hovered.png"))); // NOI18N
        getContentPane().add(buttonPPKN, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 530, -1, -1));

        buttonPJOK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Components/PJOK.png"))); // NOI18N
        buttonPJOK.setToolTipText("Button");
        buttonPJOK.setBorder(null);
        buttonPJOK.setBorderPainted(false);
        buttonPJOK.setContentAreaFilled(false);
        buttonPJOK.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonPJOK.setFocusPainted(false);
        buttonPJOK.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Components/PJOK Hovered.png"))); // NOI18N
        buttonPJOK.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Components/PJOK Hovered.png"))); // NOI18N
        getContentPane().add(buttonPJOK, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 530, -1, -1));

        buttonPKK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Components/PKK.png"))); // NOI18N
        buttonPKK.setToolTipText("Button");
        buttonPKK.setBorder(null);
        buttonPKK.setBorderPainted(false);
        buttonPKK.setContentAreaFilled(false);
        buttonPKK.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonPKK.setFocusPainted(false);
        buttonPKK.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Components/PKK Hovered.png"))); // NOI18N
        buttonPKK.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Components/PKK.png"))); // NOI18N
        getContentPane().add(buttonPKK, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 530, -1, -1));

        buttonIndo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Components/Bahasa Indonesia.png"))); // NOI18N
        buttonIndo.setToolTipText("Button");
        buttonIndo.setBorder(null);
        buttonIndo.setBorderPainted(false);
        buttonIndo.setContentAreaFilled(false);
        buttonIndo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonIndo.setFocusPainted(false);
        buttonIndo.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Components/Bahasa Indonesia Hovered.png"))); // NOI18N
        buttonIndo.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Components/Bahasa Indonesia Hovered.png"))); // NOI18N
        getContentPane().add(buttonIndo, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 530, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Components/Background.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mapelPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mapelPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mapelPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mapelPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mapelPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel background;
    private javax.swing.JButton buttonAgama;
    private javax.swing.JButton buttonDB;
    private javax.swing.JButton buttonEnglish;
    private javax.swing.JButton buttonIndo;
    private javax.swing.JButton buttonMath;
    private javax.swing.JButton buttonPBO;
    private javax.swing.JButton buttonPJOK;
    private javax.swing.JButton buttonPKK;
    private javax.swing.JButton buttonPKKrpl;
    private javax.swing.JButton buttonPPKN;
    private javax.swing.JButton buttonPPL;
    private javax.swing.JButton buttonPWPB;
    public javax.swing.JLabel header;
    // End of variables declaration//GEN-END:variables
}
