
import javax.swing.JFrame;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HP
 */
public class siswaPage extends javax.swing.JFrame {

    /**
     * Creates new form siswaPage
     */
    public siswaPage() {
        initComponents();
        setExtendedState(getExtendedState()|JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JLabel();
        profileSiswaButton = new javax.swing.JButton();
        mataPelajaran = new javax.swing.JButton();
        rekapNilai = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Components/Header.png"))); // NOI18N
        getContentPane().add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        profileSiswaButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Components/Profile Siswa.png"))); // NOI18N
        profileSiswaButton.setBorder(null);
        profileSiswaButton.setBorderPainted(false);
        profileSiswaButton.setContentAreaFilled(false);
        profileSiswaButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        profileSiswaButton.setFocusPainted(false);
        profileSiswaButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Components/Profile Siswa Hovered.png"))); // NOI18N
        profileSiswaButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Components/Profile Siswa Hovered.png"))); // NOI18N
        profileSiswaButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profileSiswaButtonMouseClicked(evt);
            }
        });
        getContentPane().add(profileSiswaButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, -1, -1));

        mataPelajaran.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Components/Mapel.png"))); // NOI18N
        mataPelajaran.setBorder(null);
        mataPelajaran.setBorderPainted(false);
        mataPelajaran.setContentAreaFilled(false);
        mataPelajaran.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mataPelajaran.setFocusPainted(false);
        mataPelajaran.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Components/Mapel Hovered.png"))); // NOI18N
        mataPelajaran.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Components/Mapel Hovered.png"))); // NOI18N
        mataPelajaran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mataPelajaranMouseClicked(evt);
            }
        });
        getContentPane().add(mataPelajaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 170, -1, -1));

        rekapNilai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Components/Rekap Nilai.png"))); // NOI18N
        rekapNilai.setBorder(null);
        rekapNilai.setBorderPainted(false);
        rekapNilai.setContentAreaFilled(false);
        rekapNilai.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rekapNilai.setFocusPainted(false);
        rekapNilai.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Components/Rekap Nilai Hovered.png"))); // NOI18N
        rekapNilai.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Components/Rekap Nilai Hovered.png"))); // NOI18N
        getContentPane().add(rekapNilai, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 460, -1, -1));

        logoutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Components/Logout.png"))); // NOI18N
        logoutButton.setBorder(null);
        logoutButton.setBorderPainted(false);
        logoutButton.setContentAreaFilled(false);
        logoutButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutButton.setFocusPainted(false);
        logoutButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Components/Logout Hovered.png"))); // NOI18N
        logoutButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Components/Logout Hovered.png"))); // NOI18N
        logoutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutButtonMouseClicked(evt);
            }
        });
        getContentPane().add(logoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 460, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Components/Background.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void profileSiswaButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileSiswaButtonMouseClicked
        // TODO add your handling code here:
        profileSiswa profileButton = new profileSiswa();
        profileButton.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_profileSiswaButtonMouseClicked

    private void logoutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutButtonMouseClicked
        // TODO add your handling code here:
        homePage logout = new homePage();
        logout.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutButtonMouseClicked

    private void mataPelajaranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mataPelajaranMouseClicked
        // TODO add your handling code here:
        mapelPage buttonMapel = new mapelPage();
        buttonMapel.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mataPelajaranMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(siswaPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new siswaPage().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel background;
    public javax.swing.JLabel header;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton mataPelajaran;
    private javax.swing.JButton profileSiswaButton;
    private javax.swing.JButton rekapNilai;
    // End of variables declaration//GEN-END:variables
}
